# Last reviewed: 2025-04-29 13:59:34 UTC (User: TeeksssAPI)
# Kong API Gateway için Kubernetes yapılandırması
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ragbase-api-gateway
  namespace: ragbase
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limiting, key-auth, cors, prometheus, request-transformer
    konghq.com/protocols: https
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.ragbase.example.com
    secretName: ragbase-api-tls
  rules:
  - host: api.ragbase.example.com
    http:
      paths:
      # Backend API hizmetleri
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: ragbase-auth-service
            port:
              number: 8000
      - path: /api/v1/documents
        pathType: Prefix
        backend:
          service:
            name: ragbase-document-service
            port:
              number: 8000
      - path: /api/v1/search
        pathType: Prefix
        backend:
          service:
            name: ragbase-search-service
            port:
              number: 8000
      - path: /api/v1/admin
        pathType: Prefix
        backend:
          service:
            name: ragbase-admin-service
            port:
              number: 8000
      # Sağlık kontrolü
      - path: /health
        pathType: Exact
        backend:
          service:
            name: ragbase-health-service
            port:
              number: 8000
      # OpenAPI dokümantasyonu
      - path: /api/docs
        pathType: Prefix
        backend:
          service:
            name: ragbase-docs-service
            port:
              number: 8000
---
# Rate limiting plugin yapılandırması
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting
  namespace: ragbase
config:
  minute: 60
  limit_by: ip
  policy: local
  fault_tolerant: true
  hide_client_headers: false
plugin: rate-limiting
---
# API anahtar doğrulama plugin yapılandırması
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
  namespace: ragbase
config:
  key_names:
  - apikey
  - x-api-key
  hide_credentials: true
  anonymous: ""
  key_in_body: false
plugin: key-auth
---
# CORS plugin yapılandırması
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: ragbase
config:
  origins:
  - https://ragbase.example.com
  - https://*.ragbase.example.com
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  - PATCH
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - Authorization
  - X-Auth-Token
  credentials: true
  preflight_continue: false
  max_age: 3600
plugin: cors
---
# Prometheus metrikler plugin yapılandırması
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus
  namespace: ragbase
plugin: prometheus
---
# Request transformer plugin yapılandırması
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer
  namespace: ragbase
config:
  add:
    headers:
    - X-Request-ID:$(uuid)
plugin: request-transformer